docs: provide full sample

diff --git a/roles/pihero/files/bin/hero b/roles/pihero/files/bin/hero
--- a/roles/pihero/files/bin/hero
+++ b/roles/pihero/files/bin/hero
@@ -6,12 +6,12 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 source "$SCRIPT_DIR/../lib/lib.bash"
 
 declare hero
-printf -v hero '\033[33m─=≡\033[91mΣ\033[90m\033[101m((\033[30m\033[43m[ \033[31m蓬\033[30m•\033[91mｏ\033[30m•]\033[0m\033[93m⊐\033[0m'
+printf -v hero '\e[33m─=≡\e[91mΣ\e[90m\e[101m((\e[30m\e[43m[ \e[31m蓬\e[30m•\e[91mｏ\e[30m•]\e[0m\e[93m⊐\e[0m'
 
 # TODO call share with sudo
 
 main() {
-  printf "\n %s \033[1;33m%s\033[0m\n\n" "$hero" "Pi Hero" >&2
+  printf "\n %s \e[1;33m%s\e[0m\n\n" "$hero" "Pi Hero" >&2
   local cmd
   if [ $# -eq 0 ]; then
     cmd=diag
@@ -48,7 +48,7 @@ main() {
     case "${1:-}" in
     start | stop)
       lease=$(newest_dhcp_lease 2>/dev/null) || {
-        printf "\033[33mFailed to find host. No corresponding DHCP lease was found.\033[0m\n" >&2
+        printf "\e[33mFailed to find host. No corresponding DHCP lease was found.\e[0m\n" >&2
         exit 1
       }
       IFS=' ' read -ra c <<<"$lease"
@@ -56,24 +56,24 @@ main() {
       host_ip="${c[1]}" # [1]=IP, [2]=MAC, [3]=hostname
       host_name="${c[3]}"
       if [ "$1" = "start" ]; then
-        printf "Preparing \033[3m%s\033[23m to use \033[3m%s\033[23m (\033[3m%s\033[23m) as upstream...\033[0m\n" \
+        printf "Preparing \e[3m%s\e[23m to use \e[3m%s\e[23m (\e[3m%s\e[23m) as upstream...\e[0m\n" \
           "$self_name" "$host_name" "$host_ip" >&2
         if add_default_route "$host_ip" && dns_set; then
-          printf "Done \033[32m✔︎\033[0m\n" >&2
-          printf "\033[1mDon't forget to activate routing on \033[3m%s\033[23m!\033[0m\n" "$host_name" >&2
+          printf "Done \e[32m✔︎\e[0m\n" >&2
+          printf "\e[1mDon't forget to activate routing on \e[3m%s\e[23m!\e[0m\n" "$host_name" >&2
         else
-          printf "\033[31mFailed to prepare \033[3m%s\033[23m to use \033[3m%s\033[23m (\033[3m%s\033[23m) as upstream.\033[0m\n" \
+          printf "\e[31mFailed to prepare \e[3m%s\e[23m to use \e[3m%s\e[23m (\e[3m%s\e[23m) as upstream.\e[0m\n" \
             "$self_name" "$host_name" "$host_ip" >&2
           exit 1
         fi
       else
-        printf "Stopping \033[3m%s\033[23m from using \033[3m%s\033[23m (\033[3m%s\033[23m) as upstream...\033[0m\n" \
+        printf "Stopping \e[3m%s\e[23m from using \e[3m%s\e[23m (\e[3m%s\e[23m) as upstream...\e[0m\n" \
           "$self_name" "$host_name" "$host_ip" >&2
         if dns_unset && delete_default_route "$host_ip"; then
-          printf "Done \033[32m✔︎\033[0m\n" >&2
-          printf "\033[1mDon't forget to deactivate routing on \033[3m%s\033[23m!\033[0m\n" "$host_name" >&2
+          printf "Done \e[32m✔︎\e[0m\n" >&2
+          printf "\e[1mDon't forget to deactivate routing on \e[3m%s\e[23m!\e[0m\n" "$host_name" >&2
         else
-          printf "\033[31mFailed to stop \033[3m%s\033[23m from using \033[3m%s\033[23m (\033[3m%s\033[23m) as upstream.\033[0m\n" \
+          printf "\e[31mFailed to stop \e[3m%s\e[23m from using \e[3m%s\e[23m (\e[3m%s\e[23m) as upstream.\e[0m\n" \
             "$self_name" "$host_name" "$host_ip" >&2
           exit 1
         fi
@@ -81,13 +81,13 @@ main() {
       ip route show
       ;;
     *)
-      printf "Usage: %s \033[3m%s\033[23m \033[3m%s\033[23m\n" "${0##*/}" share 'start|stop' >&2
+      printf "Usage: %s \e[3m%s\e[23m \e[3m%s\e[23m\n" "${0##*/}" share 'start|stop' >&2
       exit 1
       ;;
     esac
     ;;
   *)
-    printf "Usage: %s \033[3m%s\033[23m [\033[3m%s\033[23m]\n" "${0##*/}" "diag|pan|gadget|share" "SUBCOMMANDS..." >&2
+    printf "Usage: %s \e[3m%s\e[23m [\e[3m%s\e[23m]\n" "${0##*/}" "diag|pan|gadget|share" "SUBCOMMANDS..." >&2
     exit 1
     ;;
   esac
diff --git a/roles/usb_gadget/templates/usb-gadget-diag.sh.j2 b/roles/usb_gadget/templates/usb-gadget-diag.sh.j2
--- a/roles/usb_gadget/templates/usb-gadget-diag.sh.j2
+++ b/roles/usb_gadget/templates/usb-gadget-diag.sh.j2
@@ -7,14 +7,14 @@ source "$SCRIPT_DIR/lib/lib.bash"
 
 main() {
   checks_start "USB gadget diagnostics"
-  CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || { printf "\033[31mERROR: Failed to find \033[3m%s\033[23m\033[0m\n" configfs >&2 && exit 1; }
+  CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || { printf "\e[31mERROR: Failed to find \e[3m%s\e[23m\e[0m\n" configfs >&2 && exit 1; }
 
   local -r gadget_name=${1:?gadget name missing}
   local -r config_name=${2:?config name missing}
   local -r instance_name=${3:?instance name missing}
   local -r gadget_dir="$CONFIGFS_HOME/usb_gadget/$gadget_name"
 
-  printf "\033[1mChecking USB gadget \033[3m%s\033[23m...\033[0m\n" "$gadget_name" >&2
+  printf "\e[1mChecking USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
 
   check "/boot/config.txt contains dtoverlay=dwc2" grep -q '^dtoverlay=dwc2\(,dr_mode=.*\)\?$' /boot/config.txt
   check "/boot/cmdline.txt contains modules-load=dwc2" grep -q "modules-load=dwc2" /boot/cmdline.txt
@@ -36,12 +36,12 @@ main() {
   check "usb-gadget is running" grep -q "^$(ls /sys/class/udc)$" "$gadget_dir"/UDC
 
   {% if usb_gadget_features.serial is defined %}
-  printf "\033[1mChecking serial port...\033[0m\n" >&2
+  printf "\e[1mChecking serial port...\e[0m\n" >&2
   check "usb-gadget's serial port is active" systemctl -q is-active serial-getty@ttyGS0.service
   {% endif %}
 
   {% if usb_gadget_features.ethernet is defined %}
-  printf "\033[1mChecking ethernet...\033[0m\n" >&2
+  printf "\e[1mChecking ethernet...\e[0m\n" >&2
   check "dnsmasq is installed" which dnsmasq >/dev/null
   check "dnsmasq is active" systemctl -q is-active dnsmasq.service
   check "usb0 interface exists" ip link show usb0 >/dev/null
@@ -52,31 +52,22 @@ main() {
   check "usb0 dnsmasq config is not malformed" grep -v -q "^leasefile-ro=" /etc/dnsmasq.d/usb0.conf
   {% endif %}
 
-  case $FAILURE_COUNT in
-  0)
-    printf "\033[32mAll checks passed.\033[0m\n" >&2
-    ;;
-  1)
-    printf "\033[31m1 check failed.\033[0m\n" >&2
-    ;;
-  *)
-    printf "\033[31m%d checks failed.\033[0m\n" $failed >&2
-  esac
+  check_summary
 
-  printf "\n\033[1mFurther debugging:\033[0m\n" >&2
-  printf "  - check usb-gadget's config: \033[3m%s\033[23m\n" "ls -1lAFhctR '$gadget_dir'" >&2
-  printf "  - check usb-gadget service logs: \033[3m%s\033[23m\n" "systemctl status usb-gadget.service; journalctl -b -u usb-gadget.service" >&2
-  printf "  - stop usb-gadget interactively: \033[3m%s\033[23m\n" "hero gadget stop" >&2
-  printf "  - start usb-gadget interactively: \033[3m%s\033[23m\n" "hero gadget start" >&2
+  printf "\n\e[1mFurther debugging:\e[0m\n" >&2
+  printf "  - check usb-gadget's config: \e[3m%s\e[23m\n" "ls -1lAFhctR '$gadget_dir'" >&2
+  printf "  - check usb-gadget service logs: \e[3m%s\e[23m\n" "systemctl status usb-gadget.service; journalctl -b -u usb-gadget.service" >&2
+  printf "  - stop usb-gadget interactively: \e[3m%s\e[23m\n" "hero gadget stop" >&2
+  printf "  - start usb-gadget interactively: \e[3m%s\e[23m\n" "hero gadget start" >&2
   {% if usb_gadget_features.ethernet is defined %}
-  printf "  - scan for connected hosts: \033[3m%s\033[23m\n" "command -v nmap >/dev/null 2>&1 || sudo apt-get install -yqq nmap; nmap -sn 10.10.10.11-14" >&2
-  printf "  - check networking: \033[3m%s\033[23m\n" "systemctl status networking" >&2
+  printf "  - scan for connected hosts: \e[3m%s\e[23m\n" "command -v nmap >/dev/null 2>&1 || sudo apt-get install -yqq nmap; nmap -sn 10.10.10.11-14" >&2
+  printf "  - check networking: \e[3m%s\e[23m\n" "systemctl status networking" >&2
   for service in dnsmasq; do
-    printf "  \033[1m- regarding service \033[3m%s\033[23m:\033[0m\n" "$service" >&2
-    printf "    - check status: \033[3m%s\033[23m\n" "systemctl status $service.service" >&2
-    printf "    - check logs: \033[3m%s\033[23m\n" "journalctl -b -e -u $service.service" >&2
-    printf "    - stop service: \033[3m%s\033[23m\n" "sudo systemctl stop $service.service" >&2
-    printf "    - start service interactively: \033[3m%s\033[23m\n" "$(service_start_cmdline "$service.service")" >&2
+    printf "  \e[1m- regarding service \e[3m%s\e[23m:\e[0m\n" "$service" >&2
+    printf "    - check status: \e[3m%s\e[23m\n" "systemctl status $service.service" >&2
+    printf "    - check logs: \e[3m%s\e[23m\n" "journalctl -b -e -u $service.service" >&2
+    printf "    - stop service: \e[3m%s\e[23m\n" "sudo systemctl stop $service.service" >&2
+    printf "    - start service interactively: \e[3m%s\e[23m\n" "$(service_start_cmdline "$service.service")" >&2
   done
   {% endif %}
 
diff --git a/roles/usb_gadget/templates/usb-gadget.sh.j2 b/roles/usb_gadget/templates/usb-gadget.sh.j2
--- a/roles/usb_gadget/templates/usb-gadget.sh.j2
+++ b/roles/usb_gadget/templates/usb-gadget.sh.j2
@@ -6,11 +6,11 @@ declare -r gadget_name=pihero
 declare -r config_name=c.1
 declare -r instance_name=usb0
 
-CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || { printf "\033[31mERROR: Failed to find \033[3m%s\033[23m\033[0m\n" configfs >&2 && exit 1; }
+CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || { printf "\e[31mERROR: Failed to find \e[3m%s\e[23m\e[0m\n" configfs >&2 && exit 1; }
 declare -r gadget_dir="$CONFIGFS_HOME/usb_gadget/$gadget_name"
 
 start_gadget() {
-  printf "\033[1mStarting USB gadget \033[3m%s\033[23m...\033[0m\n" "$gadget_name" >&2
+  printf "\e[1mStarting USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
 
   create_gadget
   create_config
@@ -34,15 +34,15 @@ start_gadget() {
       ln -s "functions/{{ function_name }}.$instance_name" "configs/$config_name/"
     else
       rm "$post_script"
-      printf "\033[31mERROR: The function \033[3m%s.%s\033[23m failed to create. It won't be associated with configuration \033[3m%s\033[23m.\033[0m\n" \
+      printf "\e[31mERROR: The function \e[3m%s.%s\e[23m failed to create. It won't be associated with configuration \e[3m%s\e[23m.\e[0m\n" \
         '{{ function_name }}' "$instance_name" "$config_name" >&2
       local indent='    '
       local state=$(ls -1lAFhctR "functions/{{ function_name }}.$instance_name" | tail -n +2 | sed 's/^/'"$indent"'/')
-      printf "This is what \033[3m%s\033[23m looked like:\n%sDirectory %s\n%s\n" \
+      printf "This is what \e[3m%s\e[23m looked like:\n%sDirectory %s\n%s\n" \
         "functions/{{ function_name }}.$instance_name" \
         "$indent" \
         "$PWD/functions/{{ function_name }}.$instance_name" \
-        "${state:-$(printf '%s\033[3m%s\033[23m' "$indent" empty)}" >&2
+        "${state:-$(printf '%s\e[3m%s\e[23m' "$indent" empty)}" >&2
     fi
 
     ### END {{ function_name }} ###
@@ -57,29 +57,29 @@ start_gadget() {
   # Post scripts
   {% raw %}
   while (( ${#post_scripts[@]} > 0 )); do
-    printf "Running post script for function \033[3m%s.%s\033[23m...\n" "${post_scripts[0]}" "${post_scripts[1]}" >&2
+    printf "Running post script for function \e[3m%s.%s\e[23m...\n" "${post_scripts[0]}" "${post_scripts[1]}" >&2
     bash -x "${post_scripts[2]}"
     exit_code=$?
     if [ $exit_code -eq 0 ]; then
-      printf "Post script for function \033[3m%s.%s\033[23m completed successfully.\n" "${post_scripts[0]}" "${post_scripts[1]}" >&2
+      printf "Post script for function \e[3m%s.%s\e[23m completed successfully.\n" "${post_scripts[0]}" "${post_scripts[1]}" >&2
       rm "${post_scripts[2]}"
     else
-      printf "\033[31mERROR: Post script \033[3m%s\033[23m for function \033[3m%s.%s\033[23m terminated with exit code \033[3m%d\033[23m.\033[0m\n" \
+      printf "\e[31mERROR: Post script \e[3m%s\e[23m for function \e[3m%s.%s\e[23m terminated with exit code \e[3m%d\e[23m.\e[0m\n" \
         "${post_scripts[2]}" "${post_scripts[0]}" "${post_scripts[1]}" "$exit_code" >&2
     fi
     post_scripts=("${post_scripts[@]:3}")
   done
   {% endraw %}
 
-  printf "\033[1mStarted USB gadget \033[3m%s\033[23m.\033[0m\n" "$gadget_name" >&2
+  printf "\e[1mStarted USB gadget \e[3m%s\e[23m.\e[0m\n" "$gadget_name" >&2
 }
 
 # see https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html#creating-the-gadgets
 create_gadget() {
-  printf "\033[1mCreating gadget \033[3m%s\033[23m...\033[0m\n" "$gadget_name" >&2
+  printf "\e[1mCreating gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
 
-  mkdir -p "$gadget_dir" || { printf "\033[31mERROR: Failed to create directory \033[3m%s\033[23m.\033[0m\n" "$gadget_dir" >&2 && exit 1; }
-  cd "$gadget_dir" || { printf "\033[31mERROR: Failed to change directory to \033[3m%s\033[23m.\033[0m\n" "$gadget_dir" >&2 && exit 1; }
+  mkdir -p "$gadget_dir" || { printf "\e[31mERROR: Failed to create directory \e[3m%s\e[23m.\e[0m\n" "$gadget_dir" >&2 && exit 1; }
+  cd "$gadget_dir" || { printf "\e[31mERROR: Failed to change directory to \e[3m%s\e[23m.\e[0m\n" "$gadget_dir" >&2 && exit 1; }
 
   echo '0x1d6b' >idVendor  # The Linux Foundation,
                            # see https://www.usb.org/sites/default/files/usb_vids_080223.pdf
@@ -100,7 +100,7 @@ create_gadget() {
 
 # see https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html#creating-the-configurations
 create_config() {
-  printf "\033[1mCreating configuration \033[3m%s\033[23m...\033[0m\n" "$config_name" >&2
+  printf "\e[1mCreating configuration \e[3m%s\e[23m...\e[0m\n" "$config_name" >&2
 
   case "$config_name" in
   *.*)
@@ -120,7 +120,7 @@ create_config() {
     esac >configs/c.1/MaxPower
     ;;
   *)
-    printf "\033[31mERROR: The configuration needs to have the format \033[3m<name>\033[23m.\033[3m<number>\033[23m.\033[0m\n" >&2
+    printf "\e[31mERROR: The configuration needs to have the format \e[3m<name>\e[23m.\e[3m<number>\e[23m.\e[0m\n" >&2
     exit 1
     ;;
   esac
@@ -131,7 +131,7 @@ create_function() {
   local -r function_name=${1:?function name missing}
   local -r function="$function_name.$instance_name"
 
-  printf "\033[1mCreating function \033[3m%s\033[23m...\033[0m\n" "$function" >&2
+  printf "\e[1mCreating function \e[3m%s\e[23m...\e[0m\n" "$function" >&2
 
   mkdir -p "functions/$function"
 
@@ -167,7 +167,6 @@ create_function() {
     # see https://en.wikipedia.org/wiki/RNDIS
     # see https://en.wikipedia.org/wiki/Ethernet_over_USB
     # TODO test (on Windows)
-    # TODO compare with https://github.com/google/aiyprojects-raspbian-tools/blob/3abfb8d0133e44d9d215096798eb521ec31d81bd/packages/aiy-usb-gadget/gadget#L71
     echo RNDIS     >"functions/$function"/os_desc/interface.rndis/compatible_id
     echo 5162001   >"functions/$function"/os_desc/interface.rndis/sub_compatible_id
 
@@ -183,40 +182,40 @@ create_function() {
     fi'
     ;;
   *)
-    printf "\033[1mDelegating creation of function \033[3m%s\033[23m to \033[3m%s\033[23m...\033[0m\n" "$function" 'usb-gadget-custom' >&2
+    printf "\e[1mDelegating creation of function \e[3m%s\e[23m to \e[3m%s\e[23m...\e[0m\n" "$function" 'usb-gadget-custom' >&2
     (/opt/pihero/usb-gadget-custom create_custom_function "$@")
     ;;
   esac
 }
 
 bind_gadget() {
-  printf "Binding gadget in \033[3m%s\033[23m... " "$PWD" >&2
+  printf "Binding gadget in \e[3m%s\e[23m... " "$PWD" >&2
   if [ "$(cat "$gadget_dir"/UDC)" ]; then
-    printf "\033[33mWARNING: Gadget in \033[3m%s\033[23m is already bound.\033[0m\n" "$PWD" >&2
+    printf "\e[33mWARNING: Gadget in \e[3m%s\e[23m is already bound.\e[0m\n" "$PWD" >&2
   else
     ls /sys/class/udc >UDC
-    printf "\033[32m✔︎\033[0m\n" >&2
+    printf "\e[32m✔︎\e[0m\n" >&2
   fi
 }
 
 unbind_gadget() {
-  printf "Unbinding gadget in \033[3m%s\033[23m... " "$PWD" >&2
+  printf "Unbinding gadget in \e[3m%s\e[23m... " "$PWD" >&2
   if [ "$(cat "$gadget_dir"/UDC)" ]; then
     echo '' >UDC
-    printf "\033[32m✔︎\033[0m\n" >&2
+    printf "\e[32m✔︎\e[0m\n" >&2
   else
-    printf "\033[33mWARNING: No bound gadget found in \033[3m%s\033[23m.\033[0m\n" "$PWD" >&2
+    printf "\e[33mWARNING: No bound gadget found in \e[3m%s\e[23m.\e[0m\n" "$PWD" >&2
   fi
 }
 
 # see https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html#cleaning-up
 stop_gadget() {
 
-  printf "\033[1mStopping USB gadget \033[3m%s\033[23m...\033[0m\n" "$gadget_name" >&2
+  printf "\e[1mStopping USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
 
-  [ -d "$gadget_dir" ] || { printf "\033[31mERROR: USB gadget \033[3m%s\033[23m is already stopped.\033[0m\n" "$gadget_name" >&2 && exit 1; }
+  [ -d "$gadget_dir" ] || { printf "\e[31mERROR: USB gadget \e[3m%s\e[23m is already stopped.\e[0m\n" "$gadget_name" >&2 && exit 1; }
 
-  printf "\033[1mStopping serial devices...\033[0m\n" >&2
+  printf "\e[1mStopping serial devices...\e[0m\n" >&2
   while IFS= read -r -d '' f; do
     if [ -f "$f/port_num" ]; then
       N="$(cat "$f/port_num")"
@@ -227,52 +226,52 @@ stop_gadget() {
   # Unbind
   (cd "$gadget_dir" && unbind_gadget)
 
-  printf "\033[1mRemoving functions from configurations...\033[0m\n" >&2
+  printf "\e[1mRemoving functions from configurations...\e[0m\n" >&2
   for c in "$gadget_dir"/configs/*.*; do # configs/c.1
     for f in "$c"/*.*; do # configs/c.1/acm.0
       [ -h "$f" ] || continue
-      printf "Removing function \033[3m%s\033[23m from configuration \033[3m%s\033[23m.\033[0m\n" "${f##*/}" "${c##*/}" >&2
+      printf "Removing function \e[3m%s\e[23m from configuration \e[3m%s\e[23m.\e[0m\n" "${f##*/}" "${c##*/}" >&2
       rm -f "$f"
     done
   done
 
-  printf "\033[1mRemoving os_desc configurations...\033[0m\n" >&2
+  printf "\e[1mRemoving os_desc configurations...\e[0m\n" >&2
   for c in "$gadget_dir"/os_desc/*.*; do # os_desc/c.1
     [ -h "$c" ] || continue
-    printf "Removing os_desc configuration \033[3m%s\033[23m.\033[0m\n" "${c##*/}" >&2
+    printf "Removing os_desc configuration \e[3m%s\e[23m.\e[0m\n" "${c##*/}" >&2
     rm -f "$c"
   done
 
-  printf "\033[1mRemoving strings directories from configurations...\033[0m\n" >&2
+  printf "\e[1mRemoving strings directories from configurations...\e[0m\n" >&2
   for c in "$gadget_dir"/configs/*.*; do # configs/c.1
     for strings in "$c"/strings/*; do
-      printf "Removing strings directory \033[3m%s\033[23m from configuration \033[3m%s\033[23m.\033[0m\n" "${strings##*/}" "${c##*/}" >&2
+      printf "Removing strings directory \e[3m%s\e[23m from configuration \e[3m%s\e[23m.\e[0m\n" "${strings##*/}" "${c##*/}" >&2
       rmdir "$strings"
     done
   done
 
-  printf "\033[1mRemoving configurations...\033[0m\n" >&2
+  printf "\e[1mRemoving configurations...\e[0m\n" >&2
   for c in "$gadget_dir"/configs/*.*; do
-    printf "Removing configuration \033[3m%s\033[23m.\033[0m\n" "${c##*/}" >&2
+    printf "Removing configuration \e[3m%s\e[23m.\e[0m\n" "${c##*/}" >&2
     rmdir "$c"
   done
 
-  printf "\033[1mRemoving functions from the gadget...\033[0m\n" >&2
+  printf "\e[1mRemoving functions from the gadget...\e[0m\n" >&2
   for f in "$gadget_dir"/functions/*; do
-    printf "Removing function \033[3m%s\033[23m.\033[0m\n" "${f##*/}" >&2
+    printf "Removing function \e[3m%s\e[23m.\e[0m\n" "${f##*/}" >&2
     rmdir "$f"
   done
 
-  printf "\033[1mRemoving strings directories from the gadget...\033[0m\n" >&2
+  printf "\e[1mRemoving strings directories from the gadget...\e[0m\n" >&2
   for strings in "$gadget_dir"/strings/*; do
-    printf "Removing strings directory \033[3m%s\033[23m from the gadget.\033[0m\n" "${strings##*/}" >&2
+    printf "Removing strings directory \e[3m%s\e[23m from the gadget.\e[0m\n" "${strings##*/}" >&2
     rmdir "$strings"
   done
 
-  printf "\033[1mRemoving the gadget \033[3m%s\033[23m...\033[0m\n" "$gadget_name" >&2
+  printf "\e[1mRemoving the gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
   rmdir "$gadget_dir"
 
-  printf "\033[1mStopped USB gadget \033[3m%s\033[23m.\033[0m\n" "$gadget" >&2
+  printf "\e[1mStopped USB gadget \e[3m%s\e[23m.\e[0m\n" "$gadget" >&2
 }
 
 main() {
@@ -290,7 +289,7 @@ main() {
           /opt/pihero/usb-gadget-diag "$gadget_name" "$config_name" "$instance_name"
       ;;
       *)
-        printf "\033[33mUsage: %s \033[3m%s\033[23m|\033[3m%s\033[23m|\033[3m%s\033[23m\033[0m\n" "$0" start stop diag >&2
+        printf "\e[33mUsage: %s \e[3m%s\e[23m|\e[3m%s\e[23m|\e[3m%s\e[23m\e[0m\n" "$0" start stop diag >&2
         exit 1
       ;;
   esac
