feature: add interactive menu if no command is provided

diff --git a/roles/pihero/files/bin/pihero b/roles/pihero/files/bin/pihero
--- a/roles/pihero/files/bin/pihero
+++ b/roles/pihero/files/bin/pihero
@@ -7,12 +7,39 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 # shellcheck source=./../lib/lib.bash
 source "$SCRIPT_DIR/../lib/lib.bash"
 
+# Prints the Pi Hero kaomoji in the given mood.
+# Globals:
+#   None
+# Arguments:
+#   test (flag, optional): If specified, print one kaomoji for each mood.
+#   mood (string, default: neutral): The mood to use.
+# Outputs:
+#   1: The kaomoji in the given mood.
+# Returns:
+#   0: Always
 hero() {
     local mood=neutral face
-    while (($# > 0)); do
+
+    if [ $# -gt 0 ] && [ "$1" = --test ]; then
+        shift
+        local rows=()
+        for mood in neutral happy sad unknown; do
+            m=$(gum style --faint "$mood")
+            k=$(CLICOLOR_FORCE=${CLICOLOR_FORCE-1} hero --mood "$mood")
+            row=$(gum join --vertical --align center "$k" '' "$m")
+            rows+=("$(gum style --padding "1 2" "$row")")
+        done
+        gum join --vertical "${rows[@]}"
+        exit
+    fi
+
+    while [ $# -gt 0 ]; do
         case "$1" in
         --mood=*)
             mood="${1#*=}" && shift
+            ;;
+        --mood)
+            shift && mood=${1?mood: parameter value not set} && shift
             ;;
         *)
             break
@@ -34,141 +61,115 @@ hero() {
         face=('' '༶' '´⊙' '﹏' '⊙`' '')
         ;;
     esac
-    printf '\e[33m─=≡\e[91mΣ\e[90m\e[101m((\e[30m\e[43m[%s\e[31m%s\e[30m%s\e[91m%s\e[30m%s\e[31m%s\e[30m]\e[0m\e[93m⊐\e[0m' "${face[@]}"
+
+    local parts=(
+        '{{ Foreground "3" "─" }}'
+        '{{ Foreground "3" "=" }}'
+        '{{ Foreground "3" "≡" }}'
+        '{{ Foreground "9" "Σ" }}'
+        '{{ Color "8" "9" "(" }}'
+        '{{ Color "8" "9" "(" }}'
+        '{{ Color "0" "3" "[" }}'
+        '{{ Color "0" "3" "'"${face[0]}"'" }}'
+        '{{ Color "1" "3" "'"${face[1]}"'" }}'
+        '{{ Color "0" "3" "'"${face[2]}"'" }}'
+        '{{ Color "9" "3" "'"${face[3]}"'" }}'
+        '{{ Color "0" "3" "'"${face[4]}"'" }}'
+        '{{ Color "1" "3" "'"${face[5]}"'" }}'
+        '{{ Color "0" "3" "]" }}'
+        '{{ Foreground "11" "⊐" }}'
+    )
+    gum format --type template "$(printf '%s' "${parts[@]}")"
+}
+
+customize_cli() {
+    if is_tty; then
+        export DIE_TEMPLATE && DIE_TEMPLATE=" $(hero --mood sad) "'{{ Foreground "1" "%s" }}'$'\n'
+    fi
+
+    export GUM_CHOOSE_CURSOR
+    GUM_CHOOSE_CURSOR=" $(CLICOLOR_FORCE=1 hero --mood=neutral) "
+    export GUM_CHOOSE_CURSOR_FOREGROUND='11' # 3=yellow + 8=bright
 }
 
 # TODO call share with sudo
 
-extension_get() {
-    local extension="$SCRIPT_DIR/../${1?name missing}.bash"
-    if [ -f "$extension" ]; then
-        printf '%s\n' "$extension"
-        return 0
-    else
-        return 1
+main() {
+    if [ "$1" = --test ]; then
+        hero "$@"
+        exit $?
     fi
-}
 
-extension_invoke() {
-    local extension no_header=0
-    while (($# > 0)); do
-        case "$1" in
-        --no-header)
-            no_header=1 && shift
-            ;;
-        *)
-            break
-            ;;
-        esac
+    customize_cli
+    local extension_dirs=("$SCRIPT_DIR/..")
+    local extensions && mapfile -t extensions < <(list_extensions "${extension_dirs[@]}")
+
+    [ $# -gt 0 ] || exec_completed --name command diag "${extensions[@]}"
+    local cmd=$1 && shift
+
+    # run all diagnostics
+    if [ "$cmd" = diag ]; then
+        printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=neutral)" "Pi Hero" >&2
+        local result=0 diagnostics=()
+
+        for cmd in "${extensions[@]}"; do
+            run_extension_command "$cmd" diag "${extension_dirs[@]}"
+            diagnostics+=("$cmd" "$?")
+            printf '\n' >&2
+        done
+
+        local summary=''
+        while ((${#diagnostics[@]} > 0)); do
+            local icon
+            if [ "${diagnostics[1]}" -eq 0 ]; then
+                printf -v icon '\e[32m✔︎\e[0m'
+            else
+                printf -v icon '\e[31m✘︎\e[0m'
+                result=1
+            fi
+            printf -v summary '%s   \e[1m%s %s\e[0m' "$summary" "${diagnostics[0]}" "$icon"
+            diagnostics=("${diagnostics[@]:2}")
+        done
+        printf ' %s%s\n' "$(hero --mood="$result")" "$summary" >&2
+        printf '\n' >&2
+
+        exit "$result"
+    fi
+
+    # match extension command
+    local extension
+    for extension in "${extensions[@]}"; do
+        if [ "$cmd" = "$extension" ]; then
+            local subcommands && mapfile -t subcommands < <(list_extension_commands "$extension" "${extension_dirs[@]}")
+            [ "${#subcommands[@]}" -gt 0 ] || hero_die sad "no commands found for extension $extension"
+
+            [ $# -gt 0 ] || exec_completed --name subcommand "${subcommands[@]}" -- "$cmd"
+            local subcmd=$1 && shift
+
+            local subcommand
+            for subcommand in "${subcommands[@]}"; do
+                if [ "$subcmd" = "$subcommand" ]; then
+                    run_extension_command "$cmd" "$subcmd" "${extension_dirs[@]}" -- "$@"
+                    exit $?
+                fi
+            done
+
+            # no subcommand matched
+            usage --name subcommand "${subcommands[@]}" -- "$cmd"
+            for t in 0 1 2; do
+                if [ -t "$t" ]; then
+                    echo "t$t: yes"
+                else
+                    echo "t$t: no"
+                fi
+            done
+            die "subcommand $subcmd not found"
+        fi
     done
 
-    local cmd="${1:?command missing}" && shift
-    if ! extension=$(extension_get "$cmd"); then
-        printf "\e[31mERROR: No extension \e[3m%s\e[23m found\n" "$cmd" >&2
-        exit 124
-    fi
-
-    (
-        # shellcheck disable=SC1090
-        source "$extension"
-
-        local public=() found
-        while read -r function_declaration; do
-            local function_with_flags="${function_declaration#declare -f}"
-            local function_name="${function_with_flags#* }"
-            [ "${function_name:0:1}" = '+' ] || continue
-            [ "${function_name:1}" = 'default' ] || public+=("${function_name:1}")
-            if [ "${function_name:1}" = "${1:-default}" ]; then
-                found=$function_name
-            fi
-        done < <(declare -F)
-
-        if [ "$found" ]; then
-            [ "$no_header" = 1 ] || printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=neutral)" "$cmd${1:+ "$(printf "\e[39m%s" "$1")"}" >&2
-            "$found" "${@:2}"
-        else
-            {
-                if [ "$#" -eq 0 ]; then
-                    printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=neutral)" "$cmd"
-                else
-                    printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=sad)" "$(printf "%s \e[31m%s \e[0m%s" "$cmd" "$1" "← unknown subcommand")"
-                fi
-                {
-                    printf "\e[1mUsage: %s %s \e[3m%s\e[23m\e[0m\n" "${0##*/}" "$cmd" "subcommand"
-                    printf "\n"
-                    printf "Subcommands:\n"
-                    printf "  %s\n" "${public[@]}"
-                    printf '\n'
-                } | sed 's/^/     /'
-            } >&2
-            exit 1
-        fi
-    )
-}
-
-main() {
-    local extensions=("$SCRIPT_DIR/../"*.bash)
-    local extension_commands=("${extensions[@]##*/}") && extension_commands=("${extension_commands[@]%.bash}")
-
-    local cmd
-    if [ $# -gt 0 ]; then
-        cmd=$1 && shift
-
-        # run all diagnostics
-        if [ "$cmd" = diag ]; then
-            printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=neutral)" "Pi Hero" >&2
-            local result=0 diagnostics=()
-
-            for cmd in "${extension_commands[@]}"; do
-                extension_invoke --no-header "$cmd" diag
-                diagnostics+=("$cmd" "$?")
-                printf '\n' >&2
-            done
-
-            local summary=''
-            while ((${#diagnostics[@]} > 0)); do
-                local icon
-                if [ "${diagnostics[1]}" -eq 0 ]; then
-                    printf -v icon '\e[32m✔︎\e[0m'
-                else
-                    printf -v icon '\e[31m✘︎\e[0m'
-                    result=1
-                fi
-                printf -v summary '%s   \e[1m%s %s\e[0m' "$summary" "${diagnostics[0]}" "$icon"
-                diagnostics=("${diagnostics[@]:2}")
-            done
-            printf ' %s%s\n' "$(hero --mood="$result")" "$summary" >&2
-            printf '\n' >&2
-
-            exit "$result"
-        fi
-
-        # match extension command
-        local extension_command
-        for extension_command in "${extension_commands[@]}"; do
-            if [ "$cmd" = "$extension_command" ]; then
-                extension_invoke "$cmd" "$@"
-                exit $?
-            fi
-        done
-    fi
-
     # no command matched
-    {
-        if [ "$cmd" ]; then
-            printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=sad)" "$(printf "\e[31m%s \e[0m%s" "$cmd" "← unknown command")" >&2
-        else
-            printf "\n %s \e[1;33m%s\e[0m\n\n" "$(hero --mood=neutral)" "Pi Hero" >&2
-        fi
-        {
-            printf "\e[1mUsage: %s \e[3m%s\e[23m\e[0m\n" "${0##*/}" "command"
-            printf "\n"
-            printf "Commands:\n"
-            printf "  %s\n" diag "${extension_commands[@]}"
-            printf '\n'
-        } | sed 's/^/     /'
-    } >&2
-    exit 1
+    usage --name command diag "${extensions[@]}"
+    die "command $cmd not found"
 }
 
 main "$@"
