feature: 8bit colored kaomoji

diff --git a/patch b/patch
--- a/patch
+++ b/patch
@@ -3,7 +3,6 @@
 SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
 PREFIX=${PATCH_PREFIX-PIHERO_}
-declare params_defaulted=(PREFIX="$PREFIX")
 declare params_disabled=(PREFIX="$PREFIX")
 # Sets variable with name $1 to the value of variable $PREFIX_$1 if it exists.
 # If it doesn't, uses $2 as the default value or exits with an error message.
@@ -24,7 +23,6 @@ p() {
     fi
     local val=${!prefixed:-$default}
     printf -v "$var" '%s' "$val"
-    params_defaulted+=("$prefixed=$val")
     if [ "$val" = 1 ]; then
         params_disabled+=("$prefixed=0")
     else
@@ -37,24 +35,31 @@ p() {
 m() {
     local module=${1?module missing} && shift
     local args="$*"
-    ansible "$HOST" --become -m "$module" -a "$args"
+    local host
+    # shellcheck disable=SC2153
+    for host in $HOST; do
+        ansible "$host" --become -m "$module" -a "$args"
+    done
 }
 
 # rsync command wrapper which runs:
 # rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=120' --rsync-path='sudo rsync' "${@:1:$#-1}" "$HOST:${*: -1}"
 r() {
-    [ "$#" -ge 2 ] || {
+    [ $# -ge 2 ] || {
         printf '\e[31mAt least two parameters—the files to copy, and the destination—are required\n'
         exit 1
     }
     local src=("${@:1:$#-1}")
-    local dst="$HOST:${*: -1}"
-    printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "${src[*]}" "$dst"
-    rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=10' --rsync-path='sudo rsync' "${src[@]}" "$dst" || {
-        printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "${src[*]}" "$dst"
-        exit 1
-    }
-    printf '\e[32;1m✔\e[0m\n'
+    local host
+    for host in $HOST; do
+        local dst="$host:${*: -1}"
+        printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "${src[*]}" "$dst"
+        rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=10' --rsync-path='sudo rsync' "${src[@]}" "$dst" || {
+            printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "${src[*]}" "$dst"
+            exit 1
+        }
+        printf '\e[32;1m✔\e[0m\n'
+    done
 }
 
 # Runs this patch command with the same parameters as the current execution,
@@ -63,8 +68,8 @@ r() {
 # - given parameters, for example, MAIN=1, overrides the corresponding parameter
 continuous() {
     local env_args=("${params_disabled[@]}") paths=()
-    while [ "$#" -gt 0 ]; do
-        case "$1" in
+    while [ $# -gt 0 ]; do
+        case $1 in
         *=*) env_args+=("${PREFIX}$1") && shift ;;
         *) break ;;
         esac
@@ -97,12 +102,13 @@ main() {
     # set params
     p CONTINUOUS 0                                         # Whether to run the patch operations whenever a relevant file changes
     p HOST                                                 # The host to patch
-    p MAIN 1                                               # Whether to update the pihero entrypoint
-    p MAIN_FILES "$SCRIPT_DIR/roles/pihero/files"          # The directory containing the bin and lib directory of the pihero entrypoint
+    p MAIN 1                                               # Whether to update the pihero main component
+    p MAIN_FILES "$SCRIPT_DIR/roles/pihero/files"          # The directory containing the pihero main component files
     p SPLASH 1                                             # Whether to update the pihero splash component
-    p SPLASH_FILES "$SCRIPT_DIR/roles/pihero_splash/files" # The directory containing the files of the pihero splash component
+    p SPLASH_FILES "$SCRIPT_DIR/roles/pihero_splash/files" # The directory containing the pihero splash component files
 
     if [ "$MAIN" = 0 ] && [ "$SPLASH" = 0 ]; then
+        local params
         printf -v params '\e[3m%s\e[23m ' "${PREFIX}HOST=foo.local" "$PREFIX...=..."
         printf '\e[1mUsage: %s %s\e[0m\n' "$params" "${0##*/}"
         printf ' Hints: Add -t / --continuous to run the corresponding patch operations whenever a relevant file changes.\n'
diff --git a/roles/pihero/files/bin/pihero b/roles/pihero/files/bin/pihero
--- a/roles/pihero/files/bin/pihero
+++ b/roles/pihero/files/bin/pihero
@@ -1,124 +1,148 @@
 #!/usr/bin/env bash
 
-SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || true)")" >/dev/null 2>&1 && pwd)"
 
 # shellcheck source=./../lib/lib.bash
 . "$SCRIPT_DIR/../lib/lib.bash"
 
-# Start the application.
-# If called with a terminal connected and no provided command, a menu is displayed.
-# Otherwise, the provided command is executed, or an error is thrown.
 main() {
+    init_gum
     exec_deeplink "$@"
 
-    local command
+    local extension_dirs=("$SCRIPT_DIR/..") extensions
+    extensions=$(run_caching find_extensions "${extension_dirs[@]}") || die '%s: loading extensions failed' "${extension_dirs[*]}"
+
+    local extension_names=() _ en
+    while IFS=: read -r _ _ en; do extension_names+=("$en"); done <<<"$extensions"
+
     while [ $# -gt 0 ]; do
         case $1 in
-        --*)
-            die "The provided option %p is unknown." "$1"
+        --help | -h)
+            usage --header "Ansible setup companion tool" \
+                --arg=command "${extension_names[@]}"
+            return 0
             ;;
-        *)
-            command=$1 && shift && break
-            ;;
+        *) break ;;
         esac
     done
 
-    if is_interactive; then
-        trap 'tput cnorm' EXIT
-        print_loading_screen "Loading extensions ..." >&2
+    while [ $# -gt 0 ]; do
+        case $1 in
+        --) shift && break ;;
+        --*) die --code 2 "%s: invalid option" "$1" ;;
+        -*) die --code 2 "%s: invalid flag" "$1" ;;
+        *) break ;;
+        esac
+    done
 
-        local extensions && init_extensions
-        local commands=() _ extension_name
-        while IFS=: read -r _ _ extension_name; do
-            commands+=("$extension_name")
-        done <<<"$extensions"
-
-        init_gum
-        while true; do
-            set_gum_choose_header \
-                "" "$(tput bold || true)Pi Hero" "Esc"
-
-            if [ -z "$command" ]; then
-                if command=$(
-                    # Loading title must be less or equal the shortest extension name to make sure its overwritten by gum
-                    print_loading_screen "..." >&2
-                    gum choose --selected="${commands[0]}" "${commands[@]}"
-                ); then
-                    tput civis >&2
-                else
-                    exit 130
-                fi
-            fi
-
-            set_gum_choose_header \
-                "" "$(tput dim || true)Pi Hero" "" \
-                "" "$(tput bold || true)$command" "Esc"
-
-            local exit_code
-            run_extension --extensions "$extensions" --extension-name "$command" -- "$@"
-            exit_code=$?
-            if [ "$exit_code" -eq 130 ]; then
-                print_loading_screen "..." >&2
-                command=''
-            else
-                exit "$exit_code"
+    local command
+    if [ $# -gt 0 ]; then
+        local extension_name
+        for extension_name in "${extension_names[@]}"; do
+            if [ "$extension_name" = "$1" ]; then
+                command=$1 && shift
+                break
             fi
         done
+        if [ -z "$command" ]; then
+            "${FUNCNAME[0]}" --help
+            die --code 2 '%s: invalid command' "$1"
+        fi
+    elif is_interactive; then
+        interactive "$@"
+        return
     else
-        : "${command:?}"
-
-        local extensions && init_extensions
-
-        local exit_code
-        run_extension --extensions "$extensions" --extension-name "$command" -- "$@"
+        "${FUNCNAME[0]}" --help
+        die --code 2 'command missing'
     fi
+
+    local exit_code
+    run_extension --extensions "$extensions" --extension "$command" -- "$@"
+    exit_code=$?
+    return "$exit_code"
 }
 
-# Set the extension variable to contain the specification of all discovered extensions.
-# Looks similar to this:
-# file1:command1_a command1_b:name1
-# file2:command2_a command2_b:name2
-init_extensions() {
-    local extension_dirs=("$SCRIPT_DIR/..")
-    extensions=$(caching -- get_extensions "${extension_dirs[@]}") || die "Failed to load the extensions at %p." "${extension_dirs[*]}"
+interactive() {
+    local extension
+    trap 'tput cnorm' EXIT
+    while true; do
+        set_gum_choose_header 'Pi Hero'
+        if [ -z "$extension" ]; then
+            if extension=$(
+                # Loading title must be less or equal the shortest extension name to make sure its overwritten by gum
+                print_loading_screen "..." >&2
+                gum choose --selected="${extension_names[0]}" "${extension_names[@]}"
+            ); then
+                tput civis >&2
+            else
+                return 130
+            fi
+        fi
+
+        set_gum_choose_header 'Pi Hero' "$extension"
+        local -a extension_commands=()
+        local _ loop_extension_commands loop_extension_command loop_extension_name
+        while IFS=: read -r _ loop_extension_commands loop_extension_name; do
+            if [ "$loop_extension_name" = "$extension" ]; then
+                for loop_extension_command in $loop_extension_commands; do extension_commands+=("$loop_extension_command"); done
+                break
+            fi
+        done <<<"$extensions"
+
+        if [ "${#extension_commands[@]}" -eq 1 ] && [ "${extension_commands[0]}" = "main" ]; then
+            run_extension --extensions "$extensions" --extension "$extension"
+            extension=''
+        else
+            local extension_command
+            if extension_command=$(
+                print_loading_screen "..." >&2
+                gum choose --selected="${extension_commands[0]}" "${extension_commands[@]}"
+            ); then
+                tput civis >&2
+            else
+                extension=''
+                continue
+            fi
+
+            run_extension --extensions "$extensions" --extension "$extension" -- "$extension_command"
+            extension_command=''
+        fi
+    done
 }
 
 # Sets various environment variables that are used by the command line interface.
 # bashsupport disable=BP2001
 init_gum() {
-    local bright=8 black=0 red=1 green=2 yellow=3 blue=4 magenta=5 cyan=6 white=7
+    local neutral_hero_template && neutral_hero_template=$(hero_template --mood=neutral || true)
+    local sad_hero_template && sad_hero_template=$(hero_template --mood=sad || true)
+
+    export DIE_TEMPLATE
+    printf -v DIE_TEMPLATE '\n %s {{ Foreground "%s" "%%s" }}\n' "$sad_hero_template" "$HERO_PINK"
+
+    export CHECKS_HEADER_FOREGROUND=$HERO_YELLOW
+    export CHECKS_HORIZONTAL_LINE_FOREGROUND=$HERO_YELLOW
+    export CHECKS_CODE_FOREGROUND=$HERO_YELLOW
 
     export GUM_CHOOSE_CURSOR
-    export GUM_CHOOSE_CURSOR_FOREGROUND=$((yellow + bright))
+    printf -v GUM_CHOOSE_CURSOR ' %s ' "$(run_caching --tty gum format --type template "$neutral_hero_template" || true)"
+    export GUM_CHOOSE_CURSOR_LENGTH=18
+    export GUM_CHOOSE_HEADER_FOREGROUND=$HERO_ORANGE
+    export GUM_CHOOSE_CURSOR_FOREGROUND=$HERO_YELLOW
+    export GUM_CHOOSE_ITEM_FOREGROUND=''
 
-    export GUM_PAGER_BORDER_FOREGROUND=$((black + bright))
-    export GUM_PAGER_HELP_FOREGROUND=$((yellow))
+    export GUM_PAGER_BORDER_FOREGROUND=$HERO_ORANGE
+    export GUM_PAGER_HELP_FOREGROUND=$HERO_YELLOW
     export GUM_PAGER_HELP_FAINT=1
-    export GUM_PAGER_LINE_NUMBER_FOREGROUND=$((yellow))
+    export GUM_PAGER_LINE_NUMBER_FOREGROUND=$HERO_YELLOW
     export GUM_PAGER_LINE_NUMBER_FAINT=true
-    export GUM_PAGER_MATCH_FOREGROUND=$((red))
+    export GUM_PAGER_MATCH_FOREGROUND=$HERO_PINK
     export GUM_PAGER_MATCH_BACKGROUND=''
     export GUM_PAGER_MATCH_HIGH_FOREGROUND=''
-    export GUM_PAGER_MATCH_HIGH_BACKGROUND=$((red))
+    export GUM_PAGER_MATCH_HIGH_BACKGROUND=$HERO_PINK
 
     export GUM_SPIN_SPINNER=pulse
-    export GUM_SPIN_SPINNER_FOREGROUND=$((yellow))
+    export GUM_SPIN_SPINNER_FOREGROUND=$HERO_YELLOW
     export GUM_SPIN_TITLE_BOLD=1
-
-    export GUM_CHOOSE_CURSOR_LENGTH=18
-    if is_tty; then
-        local neutral_hero
-        neutral_hero=$(CLICOLOR_FORCE=1 caching tty -- hero --mood=neutral)
-        GUM_CHOOSE_CURSOR=" $neutral_hero "
-
-        local sad_hero
-        sad_hero=$(CLICOLOR_FORCE=1 caching tty -- hero --mood=sad)
-        export DIE_TEMPLATE=$'\n'" $sad_hero "'{{ Foreground "1" "%s" }}'$'\n'
-    else
-        local neutral_hero
-        neutral_hero=$(CLICOLOR_FORCE=1 caching notty -- hero --mood=neutral)
-        GUM_CHOOSE_CURSOR=" $neutral_hero "
-    fi
 }
 
 # Prints a loading screen that is overwritten once "gum" prints
@@ -126,32 +150,45 @@ init_gum() {
 # The loading screen can be used to provide feedback to the user,
 # for the time the app itself and the gum menu take to load.
 print_loading_screen() {
-    local title=${1+ $1}
+    local title=$1
 
     tput civis
 
-    # This is the last "screen" in the hero animation, the cleanup escape sequence—without sgr0 and cnorm.
-    # That is, it clears leftovers of previous loading screens.
-    printf $'\n\n\n\n\E[112D\E[K\E[A\E[K\E[A\E[K\E[A\E[K\E[A\E[K'
+    # Escape sequence that clears the area of the loading screen
+    # without restoring the cursor.
+    local clear_sequence
+    clear_sequence=${_HERO_ANIMATE_PRE_RENDERED[*]: -1:1}
+    clear_sequence=${clear_sequence#*:}
+    clear_sequence=${clear_sequence%%"$(tput cnorm)"*}
+    printf %s "$clear_sequence"
 
-    # This is the last screen in the hero animation.
-    # Type "pihero @hero animate-record" to make a recording and copy the second last screen.
-    # The last screen is the cleanup escape sequence.
-    # bashsupport disable=LongLine
-    printf $'\n\n \E[33m─\E[0m\E[33m=\E[0m\E[33m≡\E[0m\E[91mΣ\E[0m\E[90;101m(\E[0m\E[90;101m(\E[0m\E[30;43m[\E[0m\E[30;43m \E[0m\E[31;43m蓬\E[0m\E[30;43m•\E[0m\E[91;43mｏ\E[0m\E[30;43m•\E[0m\E[30;43m]\E[0m\E[93m⊐\E[0m'
-    [ -z "$title" ] || printf ' %s' "$title"
-    printf $'\n\n\E[112D\E[A\E[A\E[A\E[A'
+    # screen is something like \n\nXXX\n\n
+    # optional title goes here        ↑
+    local last_screen=${_HERO_ANIMATE_PRE_RENDERED[*]: -2:1}
+    last_screen=${last_screen#*:}
+    {
+        printf %s "${last_screen%$'\n'$'\n'*}"
+        [ -z "$title" ] || printf ' %s' "$title"
+        printf '\n\n'
+        printf %s "${last_screen##*$'\n'$'\n'}"
+    } >&2
 }
 
 # Sets the header used by the gum choose menu.
-# Each triple of arguments is a row with
-# - the first argument placed at the start,
-# - the second argument placed at the same column as the menu options, and
-# - the third argument placed right aligned at the end of the row.
 set_gum_choose_header() {
+    local fields=()
+    while [ $# -gt 0 ]; do
+        if [ $# -gt 1 ]; then
+            fields+=('' "$1" '')
+        else
+            fields+=('' "$1" 'Esc ⤴')
+        fi
+        shift
+    done
+
     # bashsupport disable=BP2001
     export GUM_CHOOSE_HEADER
-    printf -v GUM_CHOOSE_HEADER "\n%$((GUM_CHOOSE_CURSOR_LENGTH - 1))s %-10s %8s" "$@"
+    printf -v GUM_CHOOSE_HEADER "\n%$((${GUM_CHOOSE_CURSOR_LENGTH:-2} - 1))s %-10s %8s" "${fields[@]}"
 }
 
 main "$@"
diff --git a/roles/usb_gadget/templates/usb-gadget.sh.j2 b/roles/usb_gadget/templates/usb-gadget.sh.j2
--- a/roles/usb_gadget/templates/usb-gadget.sh.j2
+++ b/roles/usb_gadget/templates/usb-gadget.sh.j2
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # USB Gadget: https://www.kernel.org/doc/html/latest/usb/index.html
 
-SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || true)")" >/dev/null 2>&1 && pwd)"
 
 # shellcheck source=./../../pihero/files/lib/lib.bash
 . "$SCRIPT_DIR/lib/lib.bash"
@@ -11,7 +11,7 @@ declare -r gadget_name=pihero
 declare -r config_name=c.1
 declare -r instance_name=usb0
 
-CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || die "Failed to find %p" configfs
+CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || die '%s: not found' configfs
 declare -r gadget_dir="$CONFIGFS_HOME/usb_gadget/$gadget_name"
 
 start_gadget() {
@@ -84,8 +84,8 @@ start_gadget() {
 create_gadget() {
   printf "\e[1mCreating gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
 
-  mkdir -p "$gadget_dir" || die "Failed to create directory %p." "$gadget_dir"
-  cd "$gadget_dir" || die "Failed to change directory to %p." "$gadget_dir"
+  mkdir -p "$gadget_dir" || die '%s: directory creation failed' "$gadget_dir"
+  cd "$gadget_dir" || die '%s: directory change failed' "$gadget_dir"
 
   echo '0x1d6b' >idVendor  # The Linux Foundation,
                            # see https://www.usb.org/sites/default/files/usb_vids_080223.pdf
@@ -108,7 +108,7 @@ create_gadget() {
 create_config() {
   printf "\e[1mCreating configuration \e[3m%s\e[23m...\e[0m\n" "$config_name"
 
-  case "$config_name" in
+  case $config_name in
   *.*)
     mkdir -p "configs/$config_name"
     mkdir -p "configs/$config_name"/strings/0x409
@@ -126,7 +126,7 @@ create_config() {
     esac >configs/c.1/MaxPower
     ;;
   *)
-      die "The configuration name %p is invalid. It needs to have the format <name>.<number>." "$config_name"
+      die '%s: configuration name not matching <name>.<number>' "$config_name"
     ;;
   esac
 }
@@ -140,7 +140,7 @@ create_function() {
 
   mkdir -p "functions/$function"
 
-  case "$function_name" in
+  case $function_name in
   acm)
     # see https://www.kernel.org/doc/html/latest/usb/gadget-testing.html#acm-function
 
@@ -218,7 +218,7 @@ stop_gadget() {
 
   printf "\e[1mStopping USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
 
-  [ -d "$gadget_dir" ] || die "The USB gadget %p is already stopped." "$gadget_name"
+  [ -d "$gadget_dir" ] || die '%s: gadget already stopped' "$gadget_name"
 
   printf "\e[1mStopping serial devices...\e[0m\n"
   while IFS= read -r -d '' f; do
@@ -280,24 +280,38 @@ stop_gadget() {
 }
 
 main() {
-  case "${1:-}" in
-      start)
-          shift
-          start_gadget
-      ;;
-      stop)
-          shift
-          stop_gadget
-      ;;
-      diag)
-          shift
-          {{ package_dir }}/usb-gadget-diag "$gadget_name" "$config_name" "$instance_name"
-      ;;
-      *)
-        printf "\e[33mUsage: %s \e[3m%s\e[23m|\e[3m%s\e[23m|\e[3m%s\e[23m\e[0m\n" "$0" start stop diag
-        die "The provided command %p is unknown." "$1"
-      ;;
-  esac
+    while [ $# -gt 0 ]; do
+        case $1 in
+        --help | -h) usage --arg=command start stop && return 0 ;;
+        *) break ;;
+        esac
+    done
+
+    while [ $# -gt 0 ]; do
+        case $1 in
+        --) shift && break ;;
+        --*) die --code 2 "%s: invalid option" "$1" ;;
+        -*) die --code 2 "%s: invalid flag" "$1" ;;
+        *) break ;;
+        esac
+    done
+
+    local command
+    if [ $# -gt 0 ]; then
+        command=$1 && shift
+    else
+        "${FUNCNAME[0]}" --help
+        die --code 2 'command missing'
+    fi
+
+    case $command in
+    start) start_gadget "$@" ;;
+    stop) stop_gadget "$@" ;;
+    *)
+        "${FUNCNAME[0]}" --help
+        die --code 2 '%s: invalid command' "$command"
+        ;;
+    esac
 }
 
 main "$@"
