refactor: align error handling more with unix

diff --git a/patch b/patch
--- a/patch
+++ b/patch
@@ -18,7 +18,7 @@ p() {
     elif [ "$default" ]; then
         printf -v "$var" '%s' "$default"
     else
-        printf '\e[31mRequired parameter \e[3m%s\e[23m is missing.\e[0m\n' "$prefixed" >&2
+        printf '\e[31mThe required parameter \e[3m%s\e[23m is missing.\e[0m\n' "$prefixed" >&2
         printf 'Either use \e[3m%s\e[23m or run \e[3m%s\e[23m to provide it.\n' "export $prefixed=..." "$prefixed=... ${0##*/}"
         exit 1
     fi
@@ -54,7 +54,7 @@ r() {
         printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "${src[*]}" "$dst"
         exit 1
     }
-    printf '\e[32m✔︎\e[0m\n'
+    printf '\e[32;1m✔\e[0m\n'
 }
 
 # Runs this patch command with the same parameters as the current execution,
@@ -65,12 +65,8 @@ continuous() {
     local env_args=("${params_disabled[@]}") paths=()
     while [ "$#" -gt 0 ]; do
         case "$1" in
-        *=*)
-            env_args+=("${PREFIX}$1") && shift
-            ;;
-        *)
-            break
-            ;;
+        *=*) env_args+=("${PREFIX}$1") && shift ;;
+        *) break ;;
         esac
     done
     env_args+=("${PREFIX}CONTINUOUS=0")
@@ -82,7 +78,7 @@ continuous() {
         "${paths[@]}"  # paths to watch
     )
 
-    printf '\e[2mWatching \e[3m%s\e[22;23m\n' "${paths[*]}" >&2
+    printf '\e[2mWatching \e[3m%s\e[22;23m\n' "${paths[*]}"
     fswatch --print0 "${fswatch_args[@]}" | xargs -0 -n 1 -I {} env "${env_args[@]}" "$0"
 }
 
diff --git a/roles/pihero/files/bin/pihero b/roles/pihero/files/bin/pihero
--- a/roles/pihero/files/bin/pihero
+++ b/roles/pihero/files/bin/pihero
@@ -1,14 +1,110 @@
-#!/bin/bash
-
-shopt -s nullglob # expand to nothing if no match
+#!/usr/bin/env bash
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
 # shellcheck source=./../lib/lib.bash
 . "$SCRIPT_DIR/../lib/lib.bash"
 
-customize_cli() {
+# Start the application.
+# If called with a terminal connected and no provided command, a menu is displayed.
+# Otherwise, the provided command is executed, or an error is thrown.
+main() {
+    exec_deeplink "$@"
+
+    local command
+    while [ $# -gt 0 ]; do
+        case $1 in
+        --*)
+            die "The provided option %p is unknown." "$1"
+            ;;
+        *)
+            command=$1 && shift && break
+            ;;
+        esac
+    done
+
+    if is_interactive; then
+        trap 'tput cnorm' EXIT
+        print_loading_screen "Loading extensions ..." >&2
+
+        local extensions && init_extensions
+        local commands=() _ extension_name
+        while IFS=: read -r _ _ extension_name; do
+            commands+=("$extension_name")
+        done <<<"$extensions"
+
+        init_gum
+        while true; do
+            set_gum_choose_header \
+                "" "$(tput bold || true)Pi Hero" "Esc"
+
+            if [ -z "$command" ]; then
+                if command=$(
+                    # Loading title must be less or equal the shortest extension name to make sure its overwritten by gum
+                    print_loading_screen "..." >&2
+                    gum choose --selected="${commands[0]}" "${commands[@]}"
+                ); then
+                    tput civis >&2
+                else
+                    exit 130
+                fi
+            fi
+
+            set_gum_choose_header \
+                "" "$(tput dim || true)Pi Hero" "" \
+                "" "$(tput bold || true)$command" "Esc"
+
+            local exit_code
+            run_extension --extensions "$extensions" --extension-name "$command" -- "$@"
+            exit_code=$?
+            if [ "$exit_code" -eq 130 ]; then
+                print_loading_screen "..." >&2
+                command=''
+            else
+                exit "$exit_code"
+            fi
+        done
+    else
+        : "${command:?}"
+
+        local extensions && init_extensions
+
+        local exit_code
+        run_extension --extensions "$extensions" --extension-name "$command" -- "$@"
+    fi
+}
+
+# Set the extension variable to contain the specification of all discovered extensions.
+# Looks similar to this:
+# file1:command1_a command1_b:name1
+# file2:command2_a command2_b:name2
+init_extensions() {
+    local extension_dirs=("$SCRIPT_DIR/..")
+    extensions=$(caching -- get_extensions "${extension_dirs[@]}") || die "Failed to load the extensions at %p." "${extension_dirs[*]}"
+}
+
+# Sets various environment variables that are used by the command line interface.
+# bashsupport disable=BP2001
+init_gum() {
+    local bright=8 black=0 red=1 green=2 yellow=3 blue=4 magenta=5 cyan=6 white=7
+
     export GUM_CHOOSE_CURSOR
+    export GUM_CHOOSE_CURSOR_FOREGROUND=$((yellow + bright))
+
+    export GUM_PAGER_BORDER_FOREGROUND=$((black + bright))
+    export GUM_PAGER_HELP_FOREGROUND=$((yellow))
+    export GUM_PAGER_HELP_FAINT=1
+    export GUM_PAGER_LINE_NUMBER_FOREGROUND=$((yellow))
+    export GUM_PAGER_LINE_NUMBER_FAINT=true
+    export GUM_PAGER_MATCH_FOREGROUND=$((red))
+    export GUM_PAGER_MATCH_BACKGROUND=''
+    export GUM_PAGER_MATCH_HIGH_FOREGROUND=''
+    export GUM_PAGER_MATCH_HIGH_BACKGROUND=$((red))
+
+    export GUM_SPIN_SPINNER=pulse
+    export GUM_SPIN_SPINNER_FOREGROUND=$((yellow))
+    export GUM_SPIN_TITLE_BOLD=1
+
     export GUM_CHOOSE_CURSOR_LENGTH=18
     if is_tty; then
         local neutral_hero
@@ -18,7 +114,6 @@ customize_cli() {
         local sad_hero
         sad_hero=$(CLICOLOR_FORCE=1 caching tty -- hero --mood=sad)
         export DIE_TEMPLATE=$'\n'" $sad_hero "'{{ Foreground "1" "%s" }}'$'\n'
-        export GUM_CHOOSE_CURSOR_FOREGROUND='11' # 3=yellow + 8=bright
     else
         local neutral_hero
         neutral_hero=$(CLICOLOR_FORCE=1 caching notty -- hero --mood=neutral)
@@ -26,126 +121,37 @@ customize_cli() {
     fi
 }
 
-main() {
-    local debug=0
-    local time_main_start=$((${EPOCHREALTIME/./} / 1000))
-    {
-        # debugging options that should be place elsewhere
-        [ ! "$1" = --hero-moods ] || {
-            shift && hero --moods "$@"
-            exit
-        }
-        [ ! "$1" = --hero-frames ] || {
-            CLICOLOR_FORCE=1 hero_frames
-            exit
-        }
-        [ ! "$1" = --hero-animate ] || {
-            hero_animate --vertical-padding 1 --loops 1 <(CLICOLOR_FORCE=1 hero_frames) >&2
-            exit
-        }
-        [ ! "$1" = --hero-animate-pre-rendered ] || {
-            hero_animate_pre_rendered --vertical-padding 1 --loops 1 >&2
-            exit
-        }
-        [ ! "$1" = --hero-animate-pre-rendered2 ] || {
-            hero_animate_pre_rendered2 --vertical-padding 1 --loops 1 >&2
-            exit
-        }
-    }
+# Prints a loading screen that is overwritten once "gum" prints
+# its choose menu.
+# The loading screen can be used to provide feedback to the user,
+# for the time the app itself and the gum menu take to load.
+print_loading_screen() {
+    local title=${1+ $1}
 
-    local cmd
-    while [ $# -gt 0 ]; do
-        case $1 in
-        --*)
-            die "The provided option %p is unknown." "$1"
-            ;;
-        *)
-            cmd=$1 && shift && break
-            ;;
-        esac
-    done
+    tput civis
 
-    local extension_dirs=("$SCRIPT_DIR/..") extensions
-    extensions=$(caching -- get_extensions "${extension_dirs[@]}") || die "Failed to load the extensions at %p." "${extension_dirs[*]}"
+    # This is the last "screen" in the hero animation, the cleanup escape sequence—without sgr0 and cnorm.
+    # That is, it clears leftovers of previous loading screens.
+    printf $'\n\n\n\n\E[112D\E[K\E[A\E[K\E[A\E[K\E[A\E[K\E[A\E[K'
 
-    local commands=() curr_ext_file _ curr_ext_name
-    while IFS=: read -r curr_ext_file _ curr_ext_name; do
-        commands+=("$curr_ext_name")
-    done <<<"$extensions"
+    # This is the last screen in the hero animation.
+    # Type "pihero @hero animate-record" to make a recording and copy the second last screen.
+    # The last screen is the cleanup escape sequence.
+    # bashsupport disable=LongLine
+    printf $'\n\n \E[33m─\E[0m\E[33m=\E[0m\E[33m≡\E[0m\E[91mΣ\E[0m\E[90;101m(\E[0m\E[90;101m(\E[0m\E[30;43m[\E[0m\E[30;43m \E[0m\E[31;43m蓬\E[0m\E[30;43m•\E[0m\E[91;43mｏ\E[0m\E[30;43m•\E[0m\E[30;43m]\E[0m\E[93m⊐\E[0m'
+    [ -z "$title" ] || printf ' %s' "$title"
+    printf $'\n\n\E[112D\E[A\E[A\E[A\E[A'
+}
 
-    local exit_code
-    if is_interactive; then
-        local time_interactive_start=$((${EPOCHREALTIME/./} / 1000))
-
-        local animation_pid animation_start=$((${EPOCHREALTIME/./} / 1000))
-        #        if [ $# = 0 ] && is_tty; then
-        #            hero_animate_pre_rendered --vertical-padding 2 --loops 0 --cleanup 0 >&2 &
-        #            animation_pid=$!
-        #        fi
-
-        customize_cli
-
-        if [ -n "$animation_pid" ] && kill -0 "$animation_pid" 2>/dev/null; then
-            local ready_start=$((${EPOCHREALTIME/./} / 1000))
-            local elapsed=$((ready_start - animation_start))
-            #            if [ "$elapsed" -lt 1000 ]; then
-            #                sleep "0.$(printf "%03d" $((1000 - elapsed)))"
-            #            fi
-            wait "$animation_pid"
-            #                kill "$animation_pid" 2>/dev/null
-            #            kill "$animation_pid"
-        fi
-
-        local bold='' && bold=$(tput bold)
-        local dim='' && dim=$(tput dim)
-        local header_pattern="\n%$((GUM_CHOOSE_CURSOR_LENGTH - 1))s %-10s %8s"
-        while true; do
-            printf -v header "$header_pattern" \
-                "" "${bold}Pi Hero" "Esc"
-
-            local time_cmd_option_start=$((${EPOCHREALTIME/./} / 1000))
-
-            if [ -z "$cmd" ]; then
-                if ! cmd=$(gum choose --header="$header" --selected="${commands[0]}" "${commands[@]}"); then
-                    exit 130
-                fi
-                local time_cmd_option_end=$((${EPOCHREALTIME/./} / 1000))
-            fi
-
-            [ "$debug" = 0 ] || printf '%10s %10d\n' \
-                "start" "$time_main_start" \
-                "interaction" "$((time_interactive_start - time_main_start))" \
-                "option-start" "$((time_cmd_option_start - time_interactive_start))" \
-                "option-end" "$((time_cmd_option_end - time_cmd_option_start))" >&2
-
-            printf -v header "$header_pattern" \
-                "" "${dim}Pi Hero" "" \
-                "" "${bold}$cmd" "Esc"
-            (
-                GUM_CHOOSE_HEADER=$header \
-                    GUM_CHOOSE_CURSOR=$GUM_CHOOSE_CURSOR \
-                    run_extension --extensions "$extensions" --extension-name "$cmd" -- "$@"
-            )
-            exit_code=$?
-            if [ "$exit_code" -eq 130 ]; then
-                cmd=''
-            else
-                break
-            fi
-        done
-    else
-        [ -n "$cmd" ] || die --code 2 "The command to run is missing."
-        local exit_code
-        (run_extension --extensions "$extensions" --extension-name "$cmd" -- "$@")
-        exit_code=$?
-    fi
-
-    if [ "$exit_code" -ge 123 ] && [ "$exit_code" -lt 128 ]; then
-        die --code "$exit_code" "Failed to run the extension command %p." "$cmd"
-    elif [ "$exit_code" -gt 2 ]; then
-        die --code "$exit_code" "The command %p terminated with exit code %s." "$cmd" "$exit_code"
-    fi
-    exit "$exit_code"
+# Sets the header used by the gum choose menu.
+# Each triple of arguments is a row with
+# - the first argument placed at the start,
+# - the second argument placed at the same column as the menu options, and
+# - the third argument placed right aligned at the end of the row.
+set_gum_choose_header() {
+    # bashsupport disable=BP2001
+    export GUM_CHOOSE_HEADER
+    printf -v GUM_CHOOSE_HEADER "\n%$((GUM_CHOOSE_CURSOR_LENGTH - 1))s %-10s %8s" "$@"
 }
 
 main "$@"
diff --git a/roles/usb_gadget/templates/usb-gadget-diag.sh.j2 b/roles/usb_gadget/templates/usb-gadget-diag.sh.j2
--- a/roles/usb_gadget/templates/usb-gadget-diag.sh.j2
+++ b/roles/usb_gadget/templates/usb-gadget-diag.sh.j2
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
@@ -9,14 +9,14 @@ main() {
   local result
 
   checks_start "USB gadget diagnostics"
-  CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || { printf "\e[31mERROR: Failed to find \e[3m%s\e[23m\e[0m\n" configfs >&2 && exit 1; }
+  CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || die "Failed to find %p" configfs
 
   local -r gadget_name=${1:?gadget name missing}
   local -r config_name=${2:?config name missing}
   local -r instance_name=${3:?instance name missing}
   local -r gadget_dir="$CONFIGFS_HOME/usb_gadget/$gadget_name"
 
-  printf "\e[1mChecking USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
+  printf "\e[1mChecking USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
 
   check "/boot/config.txt contains dtoverlay=dwc2" grep -q '^dtoverlay=dwc2\(,dr_mode=.*\)\?$' /boot/config.txt
   check "/boot/cmdline.txt contains modules-load=dwc2" grep -q "modules-load=dwc2" /boot/cmdline.txt
@@ -37,12 +37,12 @@ main() {
   check "usb-gadget is running" grep -q "^$(ls /sys/class/udc)$" "$gadget_dir"/UDC
 
   {% if usb_gadget_features.serial is defined %}
-  printf "\e[1mChecking serial port...\e[0m\n" >&2
+  printf "\e[1mChecking serial port...\e[0m\n"
   check "usb-gadget's serial port is active" systemctl -q is-active serial-getty@ttyGS0.service
   {% endif %}
 
   {% if usb_gadget_features.ethernet is defined %}
-  printf "\e[1mChecking ethernet...\e[0m\n" >&2
+  printf "\e[1mChecking ethernet...\e[0m\n"
   check "dnsmasq is installed" which dnsmasq >/dev/null
   check "dnsmasq is active" systemctl -q is-active dnsmasq.service
   check "usb0 interface exists" ip link show usb0 >/dev/null
@@ -74,7 +74,7 @@ main() {
     done
     #{% endif %}
     :
-  } | sed 's/^/  /' >&2
+  } | sed 's/^/  /'
 
   return $result
 }
diff --git a/roles/usb_gadget/templates/usb-gadget.sh.j2 b/roles/usb_gadget/templates/usb-gadget.sh.j2
--- a/roles/usb_gadget/templates/usb-gadget.sh.j2
+++ b/roles/usb_gadget/templates/usb-gadget.sh.j2
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # USB Gadget: https://www.kernel.org/doc/html/latest/usb/index.html
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
@@ -11,11 +11,11 @@ declare -r gadget_name=pihero
 declare -r config_name=c.1
 declare -r instance_name=usb0
 
-CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || { printf "\e[31mERROR: Failed to find \e[3m%s\e[23m\e[0m\n" configfs >&2 && exit 1; }
+CONFIGFS_HOME=$(findmnt --output TARGET --noheadings configfs) || die "Failed to find %p" configfs
 declare -r gadget_dir="$CONFIGFS_HOME/usb_gadget/$gadget_name"
 
 start_gadget() {
-  printf "\e[1mStarting USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
+  printf "\e[1mStarting USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
 
   create_gadget
   create_config
@@ -62,11 +62,12 @@ start_gadget() {
   # Post scripts
   {% raw %}
   while (( ${#post_scripts[@]} > 0 )); do
-    printf "Running post script for function \e[3m%s.%s\e[23m...\n" "${post_scripts[0]}" "${post_scripts[1]}" >&2
-    bash -x "${post_scripts[2]}"
+    printf "Running post script for function \e[3m%s.%s\e[23m...\n" "${post_scripts[0]}" "${post_scripts[1]}"
+    local exit_code
+    bash "${post_scripts[2]}"
     exit_code=$?
     if [ $exit_code -eq 0 ]; then
-      printf "Post script for function \e[3m%s.%s\e[23m completed successfully.\n" "${post_scripts[0]}" "${post_scripts[1]}" >&2
+      printf "Post script for function \e[3m%s.%s\e[23m completed successfully.\n" "${post_scripts[0]}" "${post_scripts[1]}"
       rm "${post_scripts[2]}"
     else
       printf "\e[31mERROR: Post script \e[3m%s\e[23m for function \e[3m%s.%s\e[23m terminated with exit code \e[3m%d\e[23m.\e[0m\n" \
@@ -76,15 +77,15 @@ start_gadget() {
   done
   {% endraw %}
 
-  printf "\e[1mStarted USB gadget \e[3m%s\e[23m.\e[0m\n" "$gadget_name" >&2
+  printf "\e[1mStarted USB gadget \e[3m%s\e[23m.\e[0m\n" "$gadget_name"
 }
 
 # see https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html#creating-the-gadgets
 create_gadget() {
-  printf "\e[1mCreating gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
+  printf "\e[1mCreating gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
 
-  mkdir -p "$gadget_dir" || { printf "\e[31mERROR: Failed to create directory \e[3m%s\e[23m.\e[0m\n" "$gadget_dir" >&2 && exit 1; }
-  cd "$gadget_dir" || { printf "\e[31mERROR: Failed to change directory to \e[3m%s\e[23m.\e[0m\n" "$gadget_dir" >&2 && exit 1; }
+  mkdir -p "$gadget_dir" || die "Failed to create directory %p." "$gadget_dir"
+  cd "$gadget_dir" || die "Failed to change directory to %p." "$gadget_dir"
 
   echo '0x1d6b' >idVendor  # The Linux Foundation,
                            # see https://www.usb.org/sites/default/files/usb_vids_080223.pdf
@@ -105,7 +106,7 @@ create_gadget() {
 
 # see https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html#creating-the-configurations
 create_config() {
-  printf "\e[1mCreating configuration \e[3m%s\e[23m...\e[0m\n" "$config_name" >&2
+  printf "\e[1mCreating configuration \e[3m%s\e[23m...\e[0m\n" "$config_name"
 
   case "$config_name" in
   *.*)
@@ -125,8 +126,7 @@ create_config() {
     esac >configs/c.1/MaxPower
     ;;
   *)
-    printf "\e[31mERROR: The configuration needs to have the format \e[3m<name>\e[23m.\e[3m<number>\e[23m.\e[0m\n" >&2
-    exit 1
+      die "The configuration name %p is invalid. It needs to have the format <name>.<number>." "$config_name"
     ;;
   esac
 }
@@ -136,7 +136,7 @@ create_function() {
   local -r function_name=${1:?function name missing}
   local -r function="$function_name.$instance_name"
 
-  printf "\e[1mCreating function \e[3m%s\e[23m...\e[0m\n" "$function" >&2
+  printf "\e[1mCreating function \e[3m%s\e[23m...\e[0m\n" "$function"
 
   mkdir -p "functions/$function"
 
@@ -146,7 +146,7 @@ create_function() {
 
     port_num_file="$PWD/functions/$function/port_num"
     echo 'if [ -f "'$port_num_file'" ]; then
-        N="$(cat "'$port_num_file'")"
+        N="$(<"'$port_num_file'")"
         systemctl start "serial-getty@ttyGS${N}.service" &
     fi'
     ;;
@@ -163,7 +163,7 @@ create_function() {
 
     ifname_file="$PWD/functions/$function/ifname"
     echo 'if [ -f "'$ifname_file'" ]; then
-        N="$(cat "'$ifname_file'")"
+        N="$(<"'$ifname_file'")"
         ifconfig "$N" {{ usb0_cidr_address }} netmask {{ usb0_cidr_netmask }}
     fi'
     ;;
@@ -182,48 +182,48 @@ create_function() {
 
     ifname_file="$PWD/functions/$function/ifname"
     echo 'if [ -f "'$ifname_file'" ]; then
-        N="$(cat "'$ifname_file'")"
+        N="$(<"'$ifname_file'")"
         ifconfig "$N" {{ usb0_cidr_address }} netmask {{ usb0_cidr_netmask }}
     fi'
     ;;
   *)
-    printf "\e[1mDelegating creation of function \e[3m%s\e[23m to \e[3m%s\e[23m...\e[0m\n" "$function" 'usb-gadget-custom' >&2
+    printf "\e[1mDelegating creation of function \e[3m%s\e[23m to \e[3m%s\e[23m...\e[0m\n" "$function" 'usb-gadget-custom'
     ({{ package_dir }}/usb-gadget-custom create_custom_function "$@")
     ;;
   esac
 }
 
 bind_gadget() {
-  printf "Binding gadget in \e[3m%s\e[23m... " "$PWD" >&2
-  if [ "$(cat "$gadget_dir"/UDC)" ]; then
-    printf "\e[33mWARNING: Gadget in \e[3m%s\e[23m is already bound.\e[0m\n" "$PWD" >&2
+  printf "Binding gadget in \e[3m%s\e[23m... " "$PWD"
+  if [ "$(<"$gadget_dir"/UDC)" ]; then
+    printf "\e[33mWARNING: Gadget in \e[3m%s\e[23m is already bound.\e[0m\n" "$PWD"
   else
     ls /sys/class/udc >UDC
-    printf "\e[32m✔︎\e[0m\n" >&2
+    printf "\e[32;1m✔\e[0m\n"
   fi
 }
 
 unbind_gadget() {
-  printf "Unbinding gadget in \e[3m%s\e[23m... " "$PWD" >&2
-  if [ "$(cat "$gadget_dir"/UDC)" ]; then
+  printf "Unbinding gadget in \e[3m%s\e[23m... " "$PWD"
+  if [ "$(<"$gadget_dir"/UDC)" ]; then
     echo '' >UDC
-    printf "\e[32m✔︎\e[0m\n" >&2
+    printf "\e[32;1m✔\e[0m\n"
   else
-    printf "\e[33mWARNING: No bound gadget found in \e[3m%s\e[23m.\e[0m\n" "$PWD" >&2
+    printf "\e[33mWARNING: No bound gadget found in \e[3m%s\e[23m.\e[0m\n" "$PWD"
   fi
 }
 
 # see https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html#cleaning-up
 stop_gadget() {
 
-  printf "\e[1mStopping USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
+  printf "\e[1mStopping USB gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
 
-  [ -d "$gadget_dir" ] || { printf "\e[31mERROR: USB gadget \e[3m%s\e[23m is already stopped.\e[0m\n" "$gadget_name" >&2 && exit 1; }
+  [ -d "$gadget_dir" ] || die "The USB gadget %p is already stopped." "$gadget_name"
 
-  printf "\e[1mStopping serial devices...\e[0m\n" >&2
+  printf "\e[1mStopping serial devices...\e[0m\n"
   while IFS= read -r -d '' f; do
     if [ -f "$f/port_num" ]; then
-      N="$(cat "$f/port_num")"
+      N="$(<"$f/port_num")"
       systemctl stop "serial-getty@ttyGS${N}.service" || true
     fi
   done < <(find "$gadget_dir/functions" -type "d" -name "acm.*" -print0)
@@ -231,52 +231,52 @@ stop_gadget() {
   # Unbind
   (cd "$gadget_dir" && unbind_gadget)
 
-  printf "\e[1mRemoving functions from configurations...\e[0m\n" >&2
+  printf "\e[1mRemoving functions from configurations...\e[0m\n"
   for c in "$gadget_dir"/configs/*.*; do # configs/c.1
     for f in "$c"/*.*; do # configs/c.1/acm.0
       [ -h "$f" ] || continue
-      printf "Removing function \e[3m%s\e[23m from configuration \e[3m%s\e[23m.\e[0m\n" "${f##*/}" "${c##*/}" >&2
+      printf "Removing function \e[3m%s\e[23m from configuration \e[3m%s\e[23m.\e[0m\n" "${f##*/}" "${c##*/}"
       rm -f "$f"
     done
   done
 
-  printf "\e[1mRemoving os_desc configurations...\e[0m\n" >&2
+  printf "\e[1mRemoving os_desc configurations...\e[0m\n"
   for c in "$gadget_dir"/os_desc/*.*; do # os_desc/c.1
     [ -h "$c" ] || continue
-    printf "Removing os_desc configuration \e[3m%s\e[23m.\e[0m\n" "${c##*/}" >&2
+    printf "Removing os_desc configuration \e[3m%s\e[23m.\e[0m\n" "${c##*/}"
     rm -f "$c"
   done
 
-  printf "\e[1mRemoving strings directories from configurations...\e[0m\n" >&2
+  printf "\e[1mRemoving strings directories from configurations...\e[0m\n"
   for c in "$gadget_dir"/configs/*.*; do # configs/c.1
     for strings in "$c"/strings/*; do
-      printf "Removing strings directory \e[3m%s\e[23m from configuration \e[3m%s\e[23m.\e[0m\n" "${strings##*/}" "${c##*/}" >&2
+      printf "Removing strings directory \e[3m%s\e[23m from configuration \e[3m%s\e[23m.\e[0m\n" "${strings##*/}" "${c##*/}"
       rmdir "$strings"
     done
   done
 
-  printf "\e[1mRemoving configurations...\e[0m\n" >&2
+  printf "\e[1mRemoving configurations...\e[0m\n"
   for c in "$gadget_dir"/configs/*.*; do
-    printf "Removing configuration \e[3m%s\e[23m.\e[0m\n" "${c##*/}" >&2
+    printf "Removing configuration \e[3m%s\e[23m.\e[0m\n" "${c##*/}"
     rmdir "$c"
   done
 
-  printf "\e[1mRemoving functions from the gadget...\e[0m\n" >&2
+  printf "\e[1mRemoving functions from the gadget...\e[0m\n"
   for f in "$gadget_dir"/functions/*; do
-    printf "Removing function \e[3m%s\e[23m.\e[0m\n" "${f##*/}" >&2
+    printf "Removing function \e[3m%s\e[23m.\e[0m\n" "${f##*/}"
     rmdir "$f"
   done
 
-  printf "\e[1mRemoving strings directories from the gadget...\e[0m\n" >&2
+  printf "\e[1mRemoving strings directories from the gadget...\e[0m\n"
   for strings in "$gadget_dir"/strings/*; do
-    printf "Removing strings directory \e[3m%s\e[23m from the gadget.\e[0m\n" "${strings##*/}" >&2
+    printf "Removing strings directory \e[3m%s\e[23m from the gadget.\e[0m\n" "${strings##*/}"
     rmdir "$strings"
   done
 
-  printf "\e[1mRemoving the gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name" >&2
+  printf "\e[1mRemoving the gadget \e[3m%s\e[23m...\e[0m\n" "$gadget_name"
   rmdir "$gadget_dir"
 
-  printf "\e[1mStopped USB gadget \e[3m%s\e[23m.\e[0m\n" "$gadget" >&2
+  printf "\e[1mStopped USB gadget \e[3m%s\e[23m.\e[0m\n" "$gadget"
 }
 
 main() {
@@ -294,8 +294,8 @@ main() {
           {{ package_dir }}/usb-gadget-diag "$gadget_name" "$config_name" "$instance_name"
       ;;
       *)
-        printf "\e[33mUsage: %s \e[3m%s\e[23m|\e[3m%s\e[23m|\e[3m%s\e[23m\e[0m\n" "$0" start stop diag >&2
-        exit 1
+        printf "\e[33mUsage: %s \e[3m%s\e[23m|\e[3m%s\e[23m|\e[3m%s\e[23m\e[0m\n" "$0" start stop diag
+        die "The provided command %p is unknown." "$1"
       ;;
   esac
 }
